packages:
  - video

ignoredBuiltDependencies:
  - '@sentry/cli'
  - core-js
  - protobufjs
  - sharp
  - tesseract.js
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
