packages:
  - video

allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  core-js: true
  esbuild: true
  protobufjs: true
  sharp: true
  tesseract.js: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - '@sentry/cli'
  - core-js
  - protobufjs
  - sharp
  - tesseract.js
  - unrs-resolver

minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1053.0'
  - date-fns@4.3.0
  - react-hook-form@7.76.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
